/* ============================================================
   DREAMS — the single source of truth for all 15 dream species.
   Shared by the game (index.html) and the Dream Codex
   (dream-codex.html). Loaded as a plain classic script so it
   works locally over file:// as well as on a web server.

   Each entry carries both the game data (type, base stats,
   level-up moveset, flavour) and the pixel-art sprite (base
   colour `c`, palette overrides `x`, and a 16x16 `rows` grid).
   The key is the species id used throughout the game.
   ============================================================ */
const DREAMS = {
  wunschling: {
    name:'Wunschling', type:'DESIRE', emoji:'🕊️',
    base:{hp:45,atk:55,def:40,spd:60},
    moves:[[1,'Wishful Glance'],[6,'Repressed Urge'],[11,'Cathexis'],[16,'Wish Fulfillment']],
    desc:'A fledgling wish. Flutters toward whatever the heart hides.',
    c:'#e9dff0', x:{y:'#e8a13a'}, rows:[
    "                ",
    "      ooo       ",
    "     oBBBo      ",
    "    oBBBBBo     ",
    "  yyoBkBBBo     ",
    "    oBBBBBo     ",
    "   oBBBBBBBoo   ",
    "  oBllBBBBBddo  ",
    "  oBllBBBBBdddo ",
    "  oBlBBBBBBddo  ",
    "  ooBBBBBBdo    ",
    "   oBBBBBo      ",
    "    oB Bo       ",
    "    yy yy       ",
    "                ",
    "                "]},
  schattenpup: {
    name:'Schattenpup', type:'FEAR', emoji:'🐺',
    base:{hp:50,atk:60,def:45,spd:50},
    moves:[[1,'Shiver'],[6,'Night Terror'],[11,'Uncanny Stare'],[16,'Dread Howl']],
    desc:'A shadow that learned to wag. Loyal to those who face it.',
    c:'#7a5add', x:{}, rows:[
    "                ",
    "   o        o   ",
    "  odo      odo  ",
    "  oBdo    odBo  ",
    "  oBBooooooBBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBkBBBBBBkBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBBBllllBBBo  ",
    "   oBBldlBBo    ",
    "   oBBlllBBo    ",
    "    oBBBBBBo    ",
    "    oBBBBBBo    ",
    "    oBdBBdBo    ",
    "     o    o     ",
    "                "]},
  mnemochick: {
    name:'Mnemochick', type:'MEMORY', emoji:'🐣',
    base:{hp:55,atk:50,def:50,spd:45},
    moves:[[1,'Reverie Touch'],[6,'Free Association'],[11,'Screen Memory'],[16,'Total Recall']],
    desc:'Hatched from a forgotten afternoon. Remembers everything.',
    c:'#f4c542', x:{y:'#e8821e', E:'#f5ecd6', z:'#d8c9a0'}, rows:[
    "                ",
    "      oo        ",
    "     oBBBo      ",
    "    oBBBBBo     ",
    "    oBkBkBo     ",
    "    oByyyBo     ",
    "   oBBBBBBBo    ",
    "   oBBBBBBBo    ",
    "  oEEEEEEEEEo   ",
    "  oEzEEzEEzEo   ",
    "  oEEEEEEEEEo   ",
    "  oEzEEEEzEEo   ",
    "   oEEEEEEEo    ",
    "    ooooooo     ",
    "                ",
    "                "]},
  anxitoad: {
    name:'Anxitoad', type:'FEAR', emoji:'🐸',
    base:{hp:50,atk:50,def:45,spd:40},
    moves:[[1,'Shiver'],[7,'Night Terror']],
    desc:'Croaks every worry you ever postponed.',
    c:'#6fa45a', x:{W:'#ffffff'}, rows:[
    "                ",
    "    o      o    ",
    "   oWo    oWo   ",
    "  oWko    okWo  ",
    "  oWWooooooWWo  ",
    "  oBBBBBBBBBBo  ",
    " oBBBBBBBBBBBBo ",
    " oBdBBBBBBBBdBo ",
    " oBBkkkkkkkkBBo ",
    " oBBBBBBBBBBBBo ",
    "  oBBBBBBBBBBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBBdBBBBdBBo  ",
    "  oBBo    oBBo  ",
    " ooo        ooo ",
    "                "]},
  libidew: {
    name:'Libidew', type:'DESIRE', emoji:'💧',
    base:{hp:45,atk:52,def:38,spd:55},
    moves:[[1,'Wishful Glance'],[7,'Repressed Urge']],
    desc:'A droplet of pure want. Evaporates if examined too directly.',
    c:'#e06aa3', x:{}, rows:[
    "       o        ",
    "       oo       ",
    "      olBo      ",
    "      olBo      ",
    "     ollBBo     ",
    "     olBBBo     ",
    "    olBBBBBo    ",
    "    oBBBBBBo    ",
    "   oBBBBBBBBo   ",
    "   oBwkBBkwBo   ",
    "  oBBBBBBBBBBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBBBddddBBBo  ",
    "   oBBBBBBBBo   ",
    "    oBBBBBBo    ",
    "     oooooo     "]},
  reverie: {
    name:'Reverie', type:'MEMORY', emoji:'🦋',
    base:{hp:42,atk:48,def:40,spd:62},
    moves:[[1,'Reverie Touch'],[7,'Free Association'],[12,'Screen Memory']],
    desc:'A daydream with wings. Hard to pin down.',
    c:'#2aa198', x:{}, rows:[
    "      o  o      ",
    "     o    o     ",
    "   o o    o o   ",
    "  oBBodddoBBo   ",
    " oBllBdkdBllBo  ",
    " oBlwlBdBlwlBo  ",
    " oBlllBdBlllBo  ",
    "  oBBBoBoBBBo   ",
    "  oBBBoBoBBBo   ",
    " oBdddBdBdddBo  ",
    " oBdwdBdBdwdBo  ",
    " oBdddBdBdddBo  ",
    "  oBBBodoBBBo   ",
    "   ooo d ooo    ",
    "       d        ",
    "                "]},
  phobat: {
    name:'Phobat', type:'FEAR', emoji:'🦇',
    base:{hp:40,atk:55,def:35,spd:65},
    moves:[[1,'Shiver'],[7,'Night Terror'],[12,'Uncanny Stare']],
    desc:'Roosts in the attic of the mind.',
    c:'#6a55c0', x:{w:'#ffffff'}, rows:[
    "                ",
    "  oo  oBBo  oo  ",
    " odBo oBBo oBdo ",
    " odBBooBBBooBBdo",
    "odBBBBoBBBoBBBBd",
    "odlBBBkBBkBBBldo",
    " odBBBBBBBBBBdo ",
    "  odBBwwwwBBdo  ",
    "   odBBBBBBdo   ",
    "    oddBBddo    ",
    "     odddo      ",
    "      oo        ",
    "                ",
    "                ",
    "                ",
    "                "]},
  egolem: {
    name:'Egolem', type:'SYMBOL', emoji:'🗿',
    base:{hp:65,atk:55,def:70,spd:25},
    moves:[[1,'Symbol Spark'],[8,'Dream Logic'],[13,'Condensation']],
    desc:'A stone face that mediates between all the others.',
    c:'#9398a1', x:{}, rows:[
    "                ",
    "   oooooooooo   ",
    "   oBBBBBBBBo   ",
    "   oBBBBBBBBo   ",
    "   oBBBBBBBBo   ",
    "   oddddddddo   ",
    "   oddBBBBddo   ",
    "   oBBBllBBBo   ",
    "   oBBBllBBBo   ",
    "   oBBBllBBBo   ",
    "   oBBBllBBBo   ",
    "   oBBdddBBBo   ",
    "   oBBBBBBBBo   ",
    "   oddBBBBddo   ",
    "    oBBBBBBo    ",
    "     oooooo     "]},
  iddra: {
    name:'Iddra', type:'DESIRE', emoji:'🐍',
    base:{hp:55,atk:65,def:45,spd:55},
    moves:[[1,'Wishful Glance'],[8,'Repressed Urge'],[12,'Cathexis']],
    desc:'It wants. That is all it does, and it does it well.',
    c:'#d2487a', x:{y:'#e6402c'}, rows:[
    "    ooo         ",
    "   oBBBo        ",
    "   okBko        ",
    "  yoBBBo        ",
    " yy oBBo        ",
    "    oBBo        ",
    "   oBBBBo       ",
    "  oBBBBBBo      ",
    " oBBBBBBBBo     ",
    " oBBooooBBBo    ",
    " oBBo  oBBBo    ",
    " oBBo  oBBBo    ",
    " oBBBooBBBBo    ",
    "  oBBBBBBBBo    ",
    "   oBBBBBBo     ",
    "    oooooo      "]},
  superegon: {
    name:'Superegon', type:'SYMBOL', emoji:'🦉',
    base:{hp:55,atk:60,def:60,spd:50},
    moves:[[1,'Symbol Spark'],[8,'Dream Logic'],[12,'Condensation']],
    desc:'Watches. Judges. Takes notes in impeccable handwriting.',
    c:'#cb7b2a', x:{y:'#e8a13a', w:'#ffffff'}, rows:[
    "   oo      oo   ",
    "  odBo    oBdo  ",
    "  oBBBooooBBBo  ",
    " oBBBBBBBBBBBBo ",
    " oBBBBBBBBBBBBo ",
    " oBwwwBBBBwwwBo ",
    " oBwkwByyBwkwBo ",
    " oBwwwByyBwwwBo ",
    " oBBBBByyBBBBBo ",
    " oBlBlBBBBlBlBo ",
    "  oBlBlBlBlBlo  ",
    "  oBBBBBBBBBBo  ",
    "   oBBBBBBBBo   ",
    "    yyo  oyy    ",
    "                ",
    "                "]},
  oedipuff: {
    name:'Oedipuff', type:'DESIRE', emoji:'🦢',
    base:{hp:60,atk:58,def:50,spd:48},
    moves:[[1,'Wishful Glance'],[8,'Repressed Urge'],[14,'Wish Fulfillment']],
    desc:'A complex creature. Best not to ask about its family.',
    c:'#eee3f0', x:{y:'#e0822a'}, rows:[
    "       ooo      ",
    "      oBBBo     ",
    "    yyoBkBo     ",
    "    y oBBBo     ",
    "      oBBo      ",
    "      oBBo      ",
    "     oBBo       ",
    "    oBBo        ",
    "   oBBBoooo     ",
    "  oBBBBBBBBo    ",
    " oBllBBBBBBBo   ",
    " oBlllBBBBBddo  ",
    " oBBBBBBBBBddo  ",
    "  oBBBBBBBBdo   ",
    "   oBBBBBBBo    ",
    "    oooooo      "]},
  traumhirsch: {
    name:'Traumhirsch', type:'SYMBOL', emoji:'🦌',
    base:{hp:60,atk:62,def:55,spd:58},
    moves:[[1,'Symbol Spark'],[9,'Dream Logic'],[14,'Manifest Content']],
    desc:"Its antlers branch like the meanings of a single dream.",
    c:'#9c6b3f', x:{m:'#caa36a', n:'#9c7a4a'}, rows:[
    "  m   mm   m    ",
    "  mm  mm  mm    ",
    "   mm mm mm     ",
    "    mmmmmm      ",
    "   o mmmm o     ",
    "  odo mm odo    ",
    "  oBdo  odBo    ",
    "   oBBBBBBo     ",
    "   oBkBBkBo     ",
    "   oBBBBBBo     ",
    "   oBwwwwBo     ",
    "    oBwwBo      ",
    "    oBBBBo      ",
    "   oBBBBBBo     ",
    "   oBdBBdBo     ",
    "    o    o      "]},
  vergessling: {
    name:'Vergessling', type:'MEMORY', emoji:'🐙',
    base:{hp:58,atk:55,def:52,spd:40},
    moves:[[1,'Reverie Touch'],[8,'Free Association'],[13,'Total Recall']],
    desc:'Eight arms, each holding something you swore you forgot.',
    c:'#2f9fb0', x:{w:'#ffffff'}, rows:[
    "     oooooo     ",
    "   ooBBBBBBoo   ",
    "  oBBBBBBBBBBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBwkBBBBwkBo  ",
    "  oBwwBBBBwwBo  ",
    "  oBBBBBBBBBBo  ",
    "  oBBBdBBdBBBo  ",
    " oBBoBoBoBoBBo  ",
    " oBo BoBoB oBo  ",
    "oBBo oBoBo oBBo ",
    "oBo  oBoBo  oBo ",
    "oBo  oB Bo  oBo ",
    " o   o   o   o  ",
    "                ",
    "                "]},
  nachtmahr: {
    name:'Nachtmahr', type:'FEAR', emoji:'🐴',
    base:{hp:60,atk:68,def:50,spd:60},
    moves:[[1,'Night Terror'],[9,'Uncanny Stare'],[14,'Dread Howl']],
    desc:'The original night-mare. Gallops through troubled sleep.',
    c:'#6a52b8', x:{h:'#37295c', r:'#e23b5a'}, rows:[
    "   o      o     ",
    "  oBo    oBo    ",
    "  oBdo  odBo    ",
    "  oBBhhhhhhBo   ",
    " oBBBhhhhhhBBo  ",
    " oBrBBBBBBBrBo  ",
    " oBBBBBBBBBBBo  ",
    " oBBBBBBBBBBBo  ",
    "  oBBBBBBBBBo   ",
    "  oBBBBBBBBBo   ",
    "   oBBBBBBBo    ",
    "   oBlBBBlBo    ",
    "   oBkBBBkBo    ",
    "   oBBBBBBBo    ",
    "    oBBBBBo     ",
    "     ooooo      "]},
  unbewusste: {
    name:'Das Unbewusste', type:'FEAR', emoji:'🌑',
    base:{hp:80,atk:72,def:60,spd:55},
    moves:[[1,'Uncanny Stare'],[1,'Dread Howl'],[1,'Manifest Content'],[14,'Oceanic Dread']],
    desc:'The vast dark beneath every mind. It has been waiting.',
    c:'#2a2140', x:{d:'#19112e', e:'#f6e98a'}, rows:[
    "     oooooo     ",
    "   ooBBBBBBoo   ",
    "  oBBdBBBBdBBo  ",
    " oBeBBBBBBBeBBo ",
    " oBBBBdeBBBBBBo ",
    "oBeBBBBBBBeBBBdo",
    "oBBBBeBBBBBBBBBo",
    "oBdBBBBBeBBBeBBo",
    "oBBeBBBBBBBBeBBo",
    "oBBBBBeBBBBBBBdo",
    " oBeBBBBBBBeBBo ",
    " oBBBdBBeBBBBBo ",
    "  oBBeBBBBBBBo  ",
    "   ooBBBBBBoo   ",
    "     oooooo     ",
    "                "]},
};

// Make available to the game in both the browser (classic script global)
// and the headless Node smoke test (which evals this file's source).
if (typeof module !== 'undefined' && module.exports) module.exports = { DREAMS };
